platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4’
pod 'SDWebImage', '~> 3.7.3’
pod 'GDataXML-HTML', '~> 1.2.0'
pod 'TSMessages', '~> 0.9.12’
pod 'NKOColorPickerView', '~> 0.2'
pod 'FastSocket', '~> 1.3’
pod 'CarbonKit'
pod 'HexColors'
pod 'ChameleonFramework'
pod 'MGSwipeTableCell'
pod 'MQTTKit', :git => 'https://github.com/mobile-web-messaging/MQTTKit.git'